Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,7 +59,16 @@ jobs:
 
       - name: Notify Local Endpoint
         run: |
-          curl -X POST -H "Content-Type: application/json" \
-               --data '{"tag": "${{ env.NEXT_VERSION }}"}' \
-               http://192.168.9.45:8000/notify
+          STATUS=0
+          for i in {1..30}; do
+            curl -X POST -H "Content-Type: application/json" \
+                 --data '{"tag": "${{ env.NEXT_VERSION }}"}' \
+                 http://192.168.9.45:8000/notify \
+                 && STATUS=1 && break || echo "Trying to connect..."
+            sleep 1
+          done
+          if [ $STATUS -eq 0 ]; then
+            echo "Failed to connect after 30 attempts. Exiting."
+            exit 1
+          fi
 
