Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,29 +17,28 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Get package metadata
-        id: package
+      - name: Get Latest Tag
+        id: get-latest-tag
+        run: |
+          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
+          echo "Latest tag is $LATEST_TAG"
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+
+      - name: Determine Next Version
+        id: next-version
         run: |
           sudo apt-get install jq
-          PACKAGE_VERSION=$(cat package.json | jq -r .version)
-          BUILD_DATE=$(date +%s | LC_ALL=en_US.UTF-8 numfmt --grouping | sed 's/,/_/g')
-
-          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
-          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
-
-          echo "::set-output name=package-version::${PACKAGE_VERSION}"
-          echo "::set-output name=build-date::${BUILD_DATE}"
-
-      - name: Update versionInfo
-        run: |
-          cat <<EOF > libs/resources/versionInfo.generated.ts
-          // This is automatically generated file
-
-          export const BuildNumber = '${{ github.run_number }}';
-          export const BuildVersion = '${{ steps.package.outputs['package-version'] }}';
-          export const BuildDate = ${{ steps.package.outputs['build-date'] }}_000;
-          export const environment: 'dev' | 'production' = 'production';
-          EOF
+          LATEST_TAG=$(cat package.json | jq -r .version)
+          IFS='.' read -ra VERSION <<< "${LATEST_TAG}"
+          NEXT_PATCH_VERSION=$(( ${VERSION[2]} + 1 ))
+          NEXT_VERSION="${VERSION[0]}.${VERSION[1]}.$NEXT_PATCH_VERSION"
+          echo "Next version will be $NEXT_VERSION"
+          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
+          jq ".version = \"$NEXT_VERSION\"" package.json > "package_temp.json" && mv "package_temp.json" package.json
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git commit -am "Update version to $NEXT_VERSION"
+          git push
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -57,7 +56,7 @@ jobs:
           context: .
           push: true
           tags: |
-            ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.package.outputs['package-version'] }}
+            ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.NEXT_VERSION }}
             ${{ env.REGISTRY_HOSTNAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
 
       - name: Notify Local Endpoint
@@ -65,12 +64,12 @@ jobs:
           STATUS=0
           for i in {1..30}; do
             curl -X POST -H "Content-Type: application/json" \
-                 --data '{"tag": "${{ steps.package.outputs['package-version'] }}"}' \
-                 https://8a85-103-186-40-106.ngrok.io/notify \
+                 --data '{"tag": "${{ env.NEXT_VERSION }}"}' \
+                  https://7751-2401-4900-1f25-8fff-00-429-5f01.ngrok.io /notify \
                  && STATUS=1 && break || echo "Trying to connect..."
             sleep 1
           done
           if [ $STATUS -eq 0 ]; then
-            echo "Failed to connect after 30 attempts. Exiting."
+            echo "Failed to connect after 5 attempts. Exiting."
             exit 1
           fi
